#### Regressão do preço de carros

In [1]:
import pandas as pd

#### Carregar base de dados

In [2]:
base = pd.read_csv('../../data/used-cars-database/autos.csv', encoding = 'ISO-8859-1')

In [3]:
base

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
15,2016-03-11 21:39:15,KA_Lufthansa_Edition_450_VB,privat,Angebot,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN,2016-03-11 00:00:00,0,24148,2016-03-19 08:46:47
16,2016-04-01 12:46:46,Polo_6n_1_4,privat,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÜV_7/17_Scheckheftgepflegt_sehr_gute...,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
22,2016-03-23 14:52:51,Opel_Meriva_1.Hand_TÜV_3.2018,privat,Angebot,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein,2016-03-23 00:00:00,0,49716,2016-03-31 01:16:33
23,2016-03-12 19:43:07,Stadtflitzer,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÜV_04/2016,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,privat,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÜV_1/17_8fach_Bereif...,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371504,2016-03-07 17:06:35,220_cdi_Benz,privat,Angebot,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN,2016-03-07 00:00:00,0,61169,2016-03-08 21:28:38
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,privat,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371518,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,81825,2016-04-06 20:47:12
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,privat,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371521,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_TÜV_12/16,privat,Angebot,1150,control,bus,2000,manuell,0,zafira,150000,3,benzin,opel,nein,2016-03-27 00:00:00,0,26624,2016-03-29 10:17:23
371522,2016-03-21 09:50:58,Mitsubishi_Cold,privat,Angebot,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja,2016-03-21 00:00:00,0,2694,2016-03-21 10:42:49
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

### Apagar atributos que não tem relação com o preço

In [4]:
base = base.drop('dateCrawled', axis=1)
base = base.drop('dateCreated', axis=1)
base = base.drop('nrOfPictures', axis=1)
base = base.drop('postalCode', axis=1)
base = base.drop('lastSeen', axis=1)

### Atributos com muita variação não ajudam no modelo

In [5]:
base['name'].value_counts()

Ford_Fiesta                                                         657
BMW_318i                                                            627
Opel_Corsa                                                          622
Volkswagen_Golf_1.4                                                 603
BMW_316i                                                            523
BMW_320i                                                            492
Volkswagen_Polo                                                     475
Renault_Twingo                                                      447
Volkswagen_Golf                                                     428
Volkswagen_Golf_1.6                                                 413
Volkswagen_Polo_1.2                                                 412
BMW_116i                                                            394
Opel_Corsa_1.2_16V                                                  373
Opel_Corsa_B                                                        369
Opel_Astra                                                          366
Peugeot_206                                                         365
Ford_Focus                                                          361
Opel_Corsa_1.0_12V                                                  344
Renault_Twingo_1.2                                                  322
Volkswagen_Passat_Variant_1.9_TDI                                   274
Volkswagen_Golf_1.9_TDI                                             273
Opel_Astra_1.6                                                      260
Audi_A4_Avant_2.0_TDI_DPF                                           254
MINI_Mini_Cooper                                                    245
Ford_Ka                                                             242
Fiat_Punto                                                          242
Audi_A4_Avant_1.9_TDI                                               241
Audi_A4_1.6                                                         238
MINI_Mini_One                                                       233
BMW_520i                                                            226
                                                                   ...
Daihatsu_Move__preiswert_VB_zu_verkaufen                              1
Polo_6n_mit_TÜV_1.0                                                   1
Audi_A6_Avant_2.5_TDI_S_line                                          1
VW_Bora_starker_Motor_tolles_Auto                                     1
Suche_Chrysler_Stratus_2.0_Cabrio                                     1
Audi_A4_Lim.Automaik                                                  1
MINI_Cooper_Cabrio_Sport_Shzg.___Garantie_bis_10/16                   1
Hyundai_Santa_Fe_2.4_2WD.....                                         1
Mercedes_Benz_CLK_Coupe_320_Elegance++AMG_Optik++SPORT++TÜV++         1
Polo_Classic_TÜV_neu                                                  1
Seat_Alhambra_VW_Sharan                                               1
Skoda_Octavia_1.6_Combi_Ambiente/Klimatronic/1.Hd./TOP                1
OPEL_VECTRA_1.6_TÜV_09/2017_IN_EINEM_SEHR_GUTEN_ZUSTAN!!!             1
BMW_335d_M_Paket_/_NAVI_/_Keyless_/_AHK_/_Performance_/_Schaltw.      1
Verkaufe_VW_Beetle                                                    1
Subaru_Forester_zu_Verkaufen!                                         1
Audi_A6_Avant_3.0_TDI_DPF__20_Zoll__ACC__Kamera                       1
Volkswagen_Eos_2.0_TSI_Exclusiv_Xenon_BicolorLeder_Navi_18"           1
Seat_Ibiza_weiss__3__tuerig                                           1
VW_Polo_9N3_1.6_105_PS__Anhaengekupplung__Tempomat_                   1
Golf_4_schwarz_1_4_Edition                                            1
Ford_Galaxie_500_Cabrio_Oldtimer__Raritaet_V8_6.4l                    1
toyota_avensis_2.2_dti                                                1
Guenstiges_Auto_zu_Verkaufen                                          1
Golf_2_1.3l___kein_Rost___Kopfdichtungsschaden___an_Bastler           1
Renault_Kangoo_KC_1.6_16V_Tuev/AU_Neu__Maerz_2018                     1
Mercedes_Sprinter_216_CDI_9_Sitzer__Standheizung                      1
Ford_USA_Explorer_U2_BJ_1996_Benzin/LPG                               1
Opel_Corsa_1.0_12v_Scheckheft_gepflegt_96000km                        1
Opel_Astra_Cabrio_Edition_111                                         1
Name: name, Length: 233531, dtype: int64

In [6]:
base = base.drop('name', axis=1)

In [7]:
base['seller'].value_counts()

privat        371525
gewerblich         3
Name: seller, dtype: int64

In [8]:
base = base.drop('seller', axis =1)

In [9]:
base['offerType'].value_counts()

Angebot    371516
Gesuch         12
Name: offerType, dtype: int64

In [10]:
base = base.drop('offerType', axis=1)

### Carros com preço inconcistente

In [11]:
base.loc[base.price <=10]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
7,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein
40,0,test,NaN,1990,NaN,0,corsa,150000,1,benzin,opel,NaN
60,1,control,suv,1994,manuell,286,NaN,150000,11,NaN,sonstige_autos,NaN
91,1,control,limousine,1995,manuell,113,e_klasse,150000,4,diesel,mercedes_benz,nein
115,0,test,NaN,2017,manuell,0,golf,5000,12,benzin,volkswagen,NaN
119,0,test,kleinwagen,1999,NaN,0,NaN,5000,0,benzin,volkswagen,NaN
157,0,test,bus,2004,manuell,101,meriva,150000,10,lpg,opel,ja
159,0,test,NaN,2006,NaN,0,andere,5000,0,NaN,fiat,NaN
237,0,test,kombi,2001,manuell,115,mondeo,150000,0,NaN,ford,NaN
279,1,test,limousine,1990,manuell,90,80,70000,6,benzin,audi,nein
346,0,control,NaN,2005,NaN,0,polo,150000,0,benzin,volkswagen,NaN
422,1,control,NaN,2000,NaN,75,golf,90000,3,benzin,volkswagen,NaN
430,0,test,NaN,1985,NaN,0,3er,150000,0,NaN,bmw,NaN
484,0,test,NaN,2016,automatik,197,3er,150000,12,diesel,bmw,nein
490,0,control,NaN,1990,NaN,0,3er,5000,0,NaN,bmw,NaN
498,0,control,NaN,2000,manuell,0,NaN,150000,0,NaN,audi,ja
543,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,volvo,NaN
545,0,control,NaN,2005,manuell,136,NaN,100000,10,NaN,toyota,NaN
588,0,control,limousine,1998,automatik,230,NaN,150000,10,benzin,saab,NaN
604,0,test,limousine,1996,manuell,170,5er,150000,0,benzin,bmw,nein
615,0,control,limousine,1997,manuell,0,3er,150000,0,benzin,bmw,NaN
642,0,test,limousine,1998,manuell,75,polo,150000,0,benzin,volkswagen,ja
649,0,control,NaN,1111,NaN,0,NaN,5000,0,NaN,opel,NaN
763,0,control,kleinwagen,2005,manuell,75,2_reihe,150000,0,benzin,peugeot,NaN
824,0,control,NaN,2000,NaN,0,astra,5000,0,benzin,opel,NaN
863,0,control,NaN,2017,manuell,105,golf,150000,0,benzin,volkswagen,NaN
897,0,test,kombi,2009,manuell,170,a6,150000,1,diesel,audi,ja
930,0,test,NaN,2016,NaN,0,andere,150000,10,diesel,citroen,NaN
941,1,control,NaN,1990,manuell,0,andere,150000,0,NaN,porsche,NaN
992,0,control,kleinwagen,2000,manuell,0,corsa,150000,5,benzin,opel,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
370511,0,test,bus,1996,automatik,110,transporter,150000,0,benzin,volkswagen,nein
370527,0,test,kleinwagen,1989,manuell,0,andere,125000,3,NaN,fiat,NaN
370530,0,test,kombi,1998,manuell,115,mondeo,20000,3,benzin,ford,nein
370599,0,test,NaN,2016,automatik,0,megane,20000,0,diesel,renault,NaN
370633,0,control,kleinwagen,1996,manuell,0,fiesta,100000,11,benzin,ford,ja
370705,0,test,coupe,1999,manuell,101,a3,150000,1,benzin,audi,nein
370710,1,control,NaN,2000,NaN,0,NaN,10000,0,NaN,sonstige_autos,NaN
370718,0,test,limousine,1983,NaN,139,golf,150000,9,benzin,volkswagen,NaN
370763,0,test,NaN,1995,manuell,204,NaN,150000,7,benzin,opel,NaN
370810,1,control,bus,1999,manuell,0,espace,150000,0,benzin,renault,NaN
370858,1,test,NaN,2000,NaN,0,NaN,150000,0,NaN,bmw,NaN
370875,0,control,kombi,2005,manuell,163,NaN,150000,3,diesel,volkswagen,NaN
371000,0,control,limousine,1995,manuell,90,mondeo,100000,1,benzin,ford,nein
371012,0,control,kleinwagen,2000,manuell,220,ka,80000,4,benzin,ford,NaN
371019,0,test,kleinwagen,1996,manuell,45,polo,150000,8,benzin,volkswagen,ja
371022,0,test,limousine,1999,automatik,224,s_klasse,150000,7,lpg,mercedes_benz,NaN
371081,0,control,limousine,1999,manuell,150,golf,125000,10,benzin,volkswagen,nein
371111,0,test,NaN,2006,NaN,0,ducato,150000,1,diesel,fiat,NaN
371134,0,test,limousine,1991,manuell,133,100,150000,6,benzin,audi,nein
371204,0,control,NaN,1970,NaN,0,sl,150000,0,NaN,mercedes_benz,NaN
371226,0,control,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN
371263,1,test,kombi,1993,automatik,217,5er,150000,12,benzin,bmw,NaN
371270,0,control,kleinwagen,2004,manuell,200,golf,150000,0,benzin,volkswagen,nein
371305,0,test,NaN,2000,manuell,55,punto,5000,5,benzin,fiat,ja
371325,0,test,NaN,1995,manuell,45,polo,150000,0,benzin,volkswagen,NaN
371356,0,control,NaN,2000,manuell,65,corsa,150000,0,NaN,opel,ja
371392,0,test,kleinwagen,2002,manuell,60,fiesta,150000,3,benzin,ford,NaN
371402,0,control,kleinwagen,1999,manuell,53,swift,150000,3,benzin,suzuki,NaN
371431,0,control,kleinwagen,1999,manuell,37,arosa,150000,7,benzin,seat,ja
371522,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja

In [12]:
base = base[base.price > 10]

In [13]:
base = base[base.price < 350000]

In [14]:
base[:10]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein
5,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja
6,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein
8,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
10,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein

### Dados nulos
- preencher com o valor de maior frequencia

In [15]:
len(base.loc[pd.isnull(base['vehicleType'])])

33546

In [16]:
base['vehicleType'].value_counts()

limousine     93614
kleinwagen    78014
kombi         65921
bus           29699
cabrio        22509
coupe         18386
suv           14477
andere         3125
Name: vehicleType, dtype: int64

In [17]:
len(base.loc[pd.isnull(base['gearbox'])])

17236

In [18]:
base['gearbox'].value_counts()

manuell      266547
automatik     75508
Name: gearbox, dtype: int64

In [19]:
len(base.loc[pd.isnull(base['model'])])

17967

In [20]:
base['model'].value_counts()

golf                  28989
andere                25560
3er                   19905
polo                  12604
corsa                 12149
astra                 10458
a4                     9972
passat                 9966
c_klasse               8624
5er                    8304
e_klasse               7379
a3                     6498
a6                     5832
focus                  5805
fiesta                 5645
transporter            5371
twingo                 4804
2_reihe                4753
fortwo                 4286
a_klasse               4241
vectra                 4072
1er                    3818
mondeo                 3503
touran                 3492
clio                   3456
3_reihe                3427
punto                  3238
zafira                 2983
megane                 2809
ibiza                  2634
                      ...
mii                      81
crossfire                66
range_rover_evoque       65
gl                       63
nubira                   61
move                     51
lybra                    50
v60                      48
145                      45
croma                    45
amarok                   39
delta                    39
terios                   35
lodgy                    35
9000                     28
charade                  27
b_max                    26
musa                     23
materia                  18
200                      17
kappa                    15
samara                   12
elefantino               11
i3                       10
kalina                    9
serie_2                   8
rangerover                6
serie_3                   3
serie_1                   1
discovery_sport           1
Name: model, Length: 251, dtype: int64

In [21]:
len(base.loc[pd.isnull(base['fuelType'])])

29391

In [22]:
base['fuelType'].value_counts()

benzin     217582
diesel     106002
lpg          5222
cng           557
hybrid        271
andere        165
elektro       101
Name: fuelType, dtype: int64

In [23]:
len(base.loc[pd.isnull(base['notRepairedDamage'])])

65986

In [24]:
base['notRepairedDamage'].value_counts()

nein    259301
ja       34004
Name: notRepairedDamage, dtype: int64

In [25]:
valores = {'vehicleType':'limousine', 'gearbox':'manuell', 'model': 'golf', 'fuelType':'benzin', 'notRepairedDamage':'nein'}

In [26]:
base = base.fillna(value = valores)

In [29]:
base.to_csv('../../data/baseCarrosProcessada.csv')

### Extrair dados de predição e o preço real

In [27]:
previsores = base.iloc[:, 1:13].values

In [28]:
preco_real = base.iloc[:, 0].values

* Transformar os atributos categoricos em numéricos

In [29]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelEncoder_previsores = LabelEncoder()

In [30]:
previsores[:,0] = labelEncoder_previsores.fit_transform(previsores[:,0])
previsores[:,1] = labelEncoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = labelEncoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = labelEncoder_previsores.fit_transform(previsores[:,5])
previsores[:,8] = labelEncoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = labelEncoder_previsores.fit_transform(previsores[:,9])
previsores[:,10] = labelEncoder_previsores.fit_transform(previsores[:,10])

In [31]:
from sklearn.compose import ColumnTransformer

In [32]:
ct = ColumnTransformer([("", OneHotEncoder(),[0,1,3,5,8,9,10])], remainder="passthrough") # The last arg ([0]) is the list of columns you want to transform in this step
previsores = ct.fit_transform(previsores)

In [33]:
previsores

<359291x316 sparse matrix of type '<class 'numpy.float64'>'
	with 3883294 stored elements in Compressed Sparse Row format>

In [34]:
previsores.shape

(359291, 316)

#### Estrutura da rede neural

In [40]:
from keras.models import Sequential
from keras.layers import Dense

In [37]:
regressor = Sequential()
regressor.add(Dense(units= 158, activation='relu', input_dim=316))
regressor.add(Dense(units= 158, activation='relu'))
regressor.add(Dense(units=1, activation='linear'))
regressor.compile(loss = 'mean_absolute_error', optimizer='adam', metrics = ['mean_absolute_error'])
regressor.fit(previsores,preco_real, batch_size=300, epochs=100)

Epoch 1/100
359291/359291 [==============================] - 10s 29us/step - loss: 3816.7278 - mean_absolute_error: 3816.7314
Epoch 2/100
359291/359291 [==============================] - 9s 26us/step - loss: 3374.0119 - mean_absolute_error: 3374.0100
Epoch 3/100
359291/359291 [==============================] - 9s 25us/step - loss: 3082.4650 - mean_absolute_error: 3082.4653
Epoch 4/100
359291/359291 [==============================] - 10s 28us/step - loss: 2907.3759 - mean_absolute_error: 2907.3760
Epoch 5/100
359291/359291 [==============================] - 11s 31us/step - loss: 2802.7867 - mean_absolute_error: 2802.7856
Epoch 6/100
359291/359291 [==============================] - 11s 32us/step - loss: 2745.2528 - mean_absolute_error: 2745.2510
Epoch 7/100
359291/359291 [==============================] - 12s 34us/step - loss: 2700.5892 - mean_absolute_error: 2700.5886
Epoch 8/100
359291/359291 [==============================] - 13s 35us/step - loss: 2656.0570 - mean_absolute_error: 2656.0552
Epoch 9/100
359291/359291 [==============================] - 12s 34us/step - loss: 2617.3612 - mean_absolute_error: 2617.3611
Epoch 10/100
359291/359291 [==============================] - 15s 42us/step - loss: 2584.1284 - mean_absolute_error: 2584.1292
Epoch 11/100
359291/359291 [==============================] - 15s 41us/step - loss: 2542.6515 - mean_absolute_error: 2542.6519
Epoch 12/100
359291/359291 [==============================] - 18s 49us/step - loss: 2522.9910 - mean_absolute_error: 2522.9907
Epoch 13/100
359291/359291 [==============================] - 12s 34us/step - loss: 2504.7168 - mean_absolute_error: 2504.7180
Epoch 14/100
359291/359291 [==============================] - 13s 35us/step - loss: 2471.2730 - mean_absolute_error: 2471.2727
Epoch 15/100
359291/359291 [==============================] - 12s 34us/step - loss: 2467.5653 - mean_absolute_error: 2467.5640
Epoch 16/100
359291/359291 [==============================] - 16s 43us/step - loss: 2463.6148 - mean_absolute_error: 2463.6152
Epoch 17/100
359291/359291 [==============================] - 13s 36us/step - loss: 2449.1962 - mean_absolute_error: 2449.1948
Epoch 18/100
359291/359291 [==============================] - 15s 41us/step - loss: 2427.7376 - mean_absolute_error: 2427.7390
Epoch 19/100
359291/359291 [==============================] - 12s 34us/step - loss: 2436.5034 - mean_absolute_error: 2436.5044
Epoch 20/100
359291/359291 [==============================] - 15s 41us/step - loss: 2440.0562 - mean_absolute_error: 2440.0554
Epoch 21/100
359291/359291 [==============================] - 15s 43us/step - loss: 2412.6938 - mean_absolute_error: 2412.6929
Epoch 22/100
359291/359291 [==============================] - 14s 39us/step - loss: 2424.3370 - mean_absolute_error: 2424.3372
Epoch 23/100
359291/359291 [==============================] - 12s 35us/step - loss: 2415.3642 - mean_absolute_error: 2415.3628
Epoch 24/100
359291/359291 [==============================] - 15s 43us/step - loss: 2388.8856 - mean_absolute_error: 2388.8870
Epoch 25/100
359291/359291 [==============================] - 12s 35us/step - loss: 2396.8445 - mean_absolute_error: 2396.8457
Epoch 26/100
359291/359291 [==============================] - 15s 41us/step - loss: 2394.8229 - mean_absolute_error: 2394.8220
Epoch 27/100
359291/359291 [==============================] - 13s 37us/step - loss: 2389.4760 - mean_absolute_error: 2389.4768
Epoch 28/100
359291/359291 [==============================] - 17s 49us/step - loss: 2378.1487 - mean_absolute_error: 2378.1492
Epoch 29/100
359291/359291 [==============================] - 18s 49us/step - loss: 2389.6636 - mean_absolute_error: 2389.6641
Epoch 30/100
359291/359291 [==============================] - 19s 54us/step - loss: 2371.1380 - mean_absolute_error: 2371.1370
Epoch 31/100
359291/359291 [==============================] - 15s 43us/step - loss: 2366.2886 - mean_absolute_error: 2366.2881
Epoch 32/100
359291/359291 [==============================] - 17s 47us/step - loss: 2362.0403 - mean_absolute_error: 2362.0410
Epoch 33/100
359291/359291 [==============================] - 14s 38us/step - loss: 2363.2432 - mean_absolute_error: 2363.2412
Epoch 34/100
359291/359291 [==============================] - 16s 45us/step - loss: 2370.5889 - mean_absolute_error: 2370.5891 0s - loss: 2370.5030 - mean_absolute_error: 237
Epoch 35/100
359291/359291 [==============================] - 20s 55us/step - loss: 2338.0612 - mean_absolute_error: 2338.0610
Epoch 36/100
359291/359291 [==============================] - 19s 53us/step - loss: 2351.0075 - mean_absolute_error: 2351.0066
Epoch 37/100
359291/359291 [==============================] - 17s 48us/step - loss: 2351.0091 - mean_absolute_error: 2351.0088
Epoch 38/100
359291/359291 [==============================] - 25s 71us/step - loss: 2338.6952 - mean_absolute_error: 2338.6960
Epoch 39/100
359291/359291 [==============================] - 22s 62us/step - loss: 2330.0155 - mean_absolute_error: 2330.0168
Epoch 40/100
359291/359291 [==============================] - 26s 73us/step - loss: 2335.6511 - mean_absolute_error: 2335.6519
Epoch 41/100
359291/359291 [==============================] - 19s 53us/step - loss: 2332.1411 - mean_absolute_error: 2332.1401
Epoch 42/100
359291/359291 [==============================] - 20s 57us/step - loss: 2326.2442 - mean_absolute_error: 2326.2458
Epoch 43/100
359291/359291 [==============================] - 21s 58us/step - loss: 2329.5101 - mean_absolute_error: 2329.5076
Epoch 44/100
359291/359291 [==============================] - 26s 72us/step - loss: 2349.5213 - mean_absolute_error: 2349.5222
Epoch 45/100
359291/359291 [==============================] - 23s 65us/step - loss: 2333.1434 - mean_absolute_error: 2333.1409
Epoch 46/100
359291/359291 [==============================] - 25s 70us/step - loss: 2326.5143 - mean_absolute_error: 2326.5125
Epoch 47/100
359291/359291 [==============================] - 41s 114us/step - loss: 2329.2777 - mean_absolute_error: 2329.27737s - - ETA: 1s - loss: 2329.2932 - mean_absolu
Epoch 48/100
359291/359291 [==============================] - 51s 142us/step - loss: 2313.7919 - mean_absolute_error: 2313.7932
Epoch 49/100
359291/359291 [==============================] - 24s 66us/step - loss: 2325.5242 - mean_absolute_error: 2325.5232
Epoch 50/100
359291/359291 [==============================] - 19s 53us/step - loss: 2313.7594 - mean_absolute_error: 2313.7585
Epoch 51/100
359291/359291 [==============================] - 17s 46us/step - loss: 2319.5426 - mean_absolute_error: 2319.5427
Epoch 52/100
359291/359291 [==============================] - 16s 45us/step - loss: 2315.8996 - mean_absolute_error: 2315.9009
Epoch 53/100
359291/359291 [==============================] - 16s 43us/step - loss: 2312.3279 - mean_absolute_error: 2312.3286
Epoch 54/100
359291/359291 [==============================] - 17s 48us/step - loss: 2309.0250 - mean_absolute_error: 2309.0244
Epoch 55/100
359291/359291 [==============================] - 17s 47us/step - loss: 2302.9321 - mean_absolute_error: 2302.9307
Epoch 56/100
359291/359291 [==============================] - 18s 50us/step - loss: 2314.8283 - mean_absolute_error: 2314.8284
Epoch 57/100
359291/359291 [==============================] - 18s 51us/step - loss: 2299.6499 - mean_absolute_error: 2299.6511
Epoch 58/100
359291/359291 [==============================] - 19s 53us/step - loss: 2294.2925 - mean_absolute_error: 2294.2915
Epoch 59/100
359291/359291 [==============================] - 17s 47us/step - loss: 2299.1247 - mean_absolute_error: 2299.1228
Epoch 60/100
359291/359291 [==============================] - 17s 48us/step - loss: 2301.8694 - mean_absolute_error: 2301.8691
Epoch 61/100
359291/359291 [==============================] - 15s 43us/step - loss: 2306.3762 - mean_absolute_error: 2306.3767
Epoch 62/100
359291/359291 [==============================] - 18s 49us/step - loss: 2287.3937 - mean_absolute_error: 2287.3926
Epoch 63/100
359291/359291 [==============================] - 17s 48us/step - loss: 2291.1819 - mean_absolute_error: 2291.1819
Epoch 64/100
359291/359291 [==============================] - 15s 43us/step - loss: 2291.2659 - mean_absolute_error: 2291.2646
Epoch 65/100
359291/359291 [==============================] - 18s 50us/step - loss: 2288.1565 - mean_absolute_error: 2288.1582
Epoch 66/100
359291/359291 [==============================] - 19s 52us/step - loss: 2275.6903 - mean_absolute_error: 2275.6907
Epoch 67/100
359291/359291 [==============================] - 16s 45us/step - loss: 2283.0462 - mean_absolute_error: 2283.0454
Epoch 68/100
359291/359291 [==============================] - 15s 42us/step - loss: 2279.6116 - mean_absolute_error: 2279.6099
Epoch 69/100
359291/359291 [==============================] - 17s 48us/step - loss: 2287.1742 - mean_absolute_error: 2287.1748
Epoch 70/100
359291/359291 [==============================] - 18s 51us/step - loss: 2288.5027 - mean_absolute_error: 2288.5042
Epoch 71/100
359291/359291 [==============================] - 30s 82us/step - loss: 2269.1502 - mean_absolute_error: 2269.1472
Epoch 72/100
359291/359291 [==============================] - 30s 84us/step - loss: 2268.6389 - mean_absolute_error: 2268.6377 2s - loss: 2267.94
Epoch 73/100
359291/359291 [==============================] - 36s 101us/step - loss: 2267.2950 - mean_absolute_error: 2267.2976
Epoch 74/100
359291/359291 [==============================] - 21s 58us/step - loss: 2267.4239 - mean_absolute_error: 2267.4229
Epoch 75/100
359291/359291 [==============================] - 27s 76us/step - loss: 2270.7006 - mean_absolute_error: 2270.7002
Epoch 76/100
359291/359291 [==============================] - 23s 64us/step - loss: 2272.6810 - mean_absolute_error: 2272.6816
Epoch 77/100
359291/359291 [==============================] - 23s 64us/step - loss: 2269.4795 - mean_absolute_error: 2269.4807
Epoch 78/100
359291/359291 [==============================] - 21s 59us/step - loss: 2275.5248 - mean_absolute_error: 2275.5242 4s - loss: 2272.1274 - m
Epoch 79/100
359291/359291 [==============================] - 20s 57us/step - loss: 2255.1937 - mean_absolute_error: 2255.1948
Epoch 80/100
359291/359291 [==============================] - 15s 43us/step - loss: 2261.4104 - mean_absolute_error: 2261.4121
Epoch 81/100
359291/359291 [==============================] - 15s 41us/step - loss: 2258.5068 - mean_absolute_error: 2258.5071
Epoch 82/100
359291/359291 [==============================] - 13s 37us/step - loss: 2260.2388 - mean_absolute_error: 2260.2388
Epoch 83/100
359291/359291 [==============================] - 21s 59us/step - loss: 2265.0245 - mean_absolute_error: 2265.0249
Epoch 84/100
359291/359291 [==============================] - 19s 52us/step - loss: 2259.6513 - mean_absolute_error: 2259.6504
Epoch 85/100
359291/359291 [==============================] - 12s 32us/step - loss: 2262.1188 - mean_absolute_error: 2262.1204
Epoch 86/100
359291/359291 [==============================] - 14s 40us/step - loss: 2245.9592 - mean_absolute_error: 2245.9595
Epoch 87/100
359291/359291 [==============================] - 20s 56us/step - loss: 2252.5943 - mean_absolute_error: 2252.5935
Epoch 88/100
359291/359291 [==============================] - 19s 54us/step - loss: 2252.6388 - mean_absolute_error: 2252.6401
Epoch 89/100
359291/359291 [==============================] - 24s 66us/step - loss: 2248.1848 - mean_absolute_error: 2248.1858
Epoch 90/100
359291/359291 [==============================] - 22s 62us/step - loss: 2247.0146 - mean_absolute_error: 2247.0144
Epoch 91/100
359291/359291 [==============================] - 22s 60us/step - loss: 2244.7222 - mean_absolute_error: 2244.7205
Epoch 92/100
359291/359291 [==============================] - 15s 41us/step - loss: 2250.6733 - mean_absolute_error: 2250.6731
Epoch 93/100
359291/359291 [==============================] - 16s 43us/step - loss: 2242.9605 - mean_absolute_error: 2242.9609 0s - loss: 2243.4333 - mean_absolute_error
Epoch 94/100
359291/359291 [==============================] - 20s 57us/step - loss: 2239.6225 - mean_absolute_error: 2239.6228
Epoch 95/100
359291/359291 [==============================] - 24s 68us/step - loss: 2237.3372 - mean_absolute_error: 2237.3379
Epoch 96/100
359291/359291 [==============================] - 19s 53us/step - loss: 2236.9999 - mean_absolute_error: 2236.9990
Epoch 97/100
359291/359291 [==============================] - 14s 40us/step - loss: 2243.5370 - mean_absolute_error: 2243.5361
Epoch 98/100
359291/359291 [==============================] - 13s 37us/step - loss: 2247.4808 - mean_absolute_error: 2247.4795
Epoch 99/100
359291/359291 [==============================] - 21s 58us/step - loss: 2232.7748 - mean_absolute_error: 2232.7742
Epoch 100/100
359291/359291 [==============================] - ETA: 0s - loss: 2230.5595 - mean_absolute_error: 2230.559 - 18s 49us/step - loss: 2230.6314 - mean_absolute_error: 2230.6316

#### Predição para a base de teste e os resultados

In [38]:
previsoes = regressor.predict(previsores)

In [39]:
preco_real.mean()

5916.833945186492

In [40]:
previsores.mean()

404.60939321284263